src/main/java/org/openeuler/sbom/manager/constant/SbomConstants.java, src/main/java/org/openeuler/sbom/manager/controller/SbomController.java, src/main/java/org/openeuler/sbom/manager/dao/RawSbomRepository.java, src/main/java/org/openeuler/sbom/manager/model/RawSbom.java, src/main/java/org/openeuler/sbom/manager/model/vo/request/PublishSbomRequest.java, src/main/java/org/openeuler/sbom/manager/model/vo/response/PublishResultResponse.java, src/main/java/org/openeuler/sbom/manager/model/vo/response/PublishSbomResponse.java, src/main/java/org/openeuler/sbom/manager/service/SbomService.java, src/main/java/org/openeuler/sbom/manager/service/impl/SbomServiceImpl.java, src/main/java/org/openeuler/sbom/manager/utils/SbomFormat.java, src/main/java/org/openeuler/sbom/manager/utils/SbomMapperUtil.java, src/main/java/org/openeuler/sbom/manager/utils/UrlUtil.java, src/main/resources/application.properties, src/main/resources/data.sql, src/test/java/org/openeuler/sbom/manager/TestCommon.java, src/test/java/org/openeuler/sbom/manager/TestConstants.java, src/test/java/org/openeuler/sbom/manager/controller/PublishControllerTests.java, src/test/resources/application.properties
=> feat: add sbom async publish feature

src/main/java/org/opensourceway/sbom/manager/quartz/ReadSbomJob.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/main/java/org/opensourceway/sbom/manager/service/vul/impl/OssIndexServiceImpl.java
=> several bugfix

src/main/java/org/opensourceway/sbom/manager/batch/ExecutionContextUtils.java, src/main/java/org/opensourceway/sbom/manager/batch/job/JobConfiguration.java, src/main/java/org/opensourceway/sbom/manager/batch/listener/AllStepsListener.java, src/main/java/org/opensourceway/sbom/manager/batch/step/SelectWaitRawSbomStep.java, src/main/java/org/opensourceway/sbom/manager/dao/RawSbomRepository.java, src/main/java/org/opensourceway/sbom/manager/model/RawSbom.java, src/main/java/org/opensourceway/sbom/manager/model/vo/request/PublishSbomRequest.java, src/main/java/org/opensourceway/sbom/manager/quartz/RestartFailedReadJob.java, src/main/java/org/opensourceway/sbom/manager/quartz/ScheduleBatchJobConfig.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/main/java/org/opensourceway/sbom/manager/utils/SbomFormat.java, src/main/java/org/opensourceway/sbom/manager/utils/SbomSpecification.java, src/main/resources/spring-batch/sbom-read-job.xml, src/test/java/org/opensourceway/sbom/manager/controller/ExportControllerTests.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, src/test/java/org/opensourceway/sbom/manager/controller/PublishControllerTests.java, src/test/java/org/opensourceway/sbom/manager/service/SbomServiceTest.java, src/test/java/org/opensourceway/sbom/manager/service/reader/impl/spdx/SpdxWriteTest.java, src/test/java/org/opensourceway/sbom/manager/utils/JsonContainsMatcher.java, src/test/java/org/opensourceway/sbom/manager/utils/TestCommon.java, utils/src/main/java/org/opensourceway/sbom/constants/BatchContextConstants.java, utils/src/main/java/org/opensourceway/sbom/constants/SbomConstants.java
feat:
a.支持失败任务的自动重试（quartz5分钟巡检一次，最多重试3次；所有task均会被重新执行，如果已成功执行或者不是restartable将会被跳过）
b.完善rawSbom中taskStatus的状态值，全部改为大写；FAILED（失败、待重试），FAILED_FINISH（重试完成后依然失败）
fix:
a.sbomContent内容过大，PublishSbomRequest中toString方法去除sbomContent字段
b.SbomFormat、SbomSpecification新增JsonClassDescription注解，避免spring batch restart时，反序列化context报非可信对象
test:
a.支持spring batch任务重试场景
b.增强用例鲁棒性
=> feat: support to restart failed batch job

src/main/resources/spring-batch/sbom-read-job.xml
=> feat: add chunk retry config

src/main/java/org/opensourceway/sbom/manager/batch/step/CollectStatisticsStep.java, src/main/java/org/opensourceway/sbom/manager/model/Product.java, src/main/java/org/opensourceway/sbom/manager/model/ProductStatistics.java, src/main/java/org/opensourceway/sbom/manager/service/vul/impl/CveManagerServiceImpl.java, src/main/java/org/opensourceway/sbom/manager/utils/CvssSeverity.java, src/main/resources/spring-batch/sbom-read-job.xml
=> collect product statistics (package info and vulnerabilities, license info is not collected yet)

build.gradle.kts, src/test/java/org/opensourceway/sbom/manager/utils/RpmSpecParserTest.java, src/test/resources/specs/389-ds-base.spec, utils/build.gradle.kts, utils/src/main/java/org/computer/whunter/rpm/parser/LICENSE.txt, utils/src/main/java/org/computer/whunter/rpm/parser/RpmSpecParser.java
=> feat: add rpm spec parser tool

build.gradle.kts, clients/vcs/src/main/java/org/opensourceway/sbom/clients/vcs/VcsApi.java, clients/vcs/src/main/java/org/opensourceway/sbom/clients/vcs/gitee/GiteeApi.java, src/test/java/org/opensourceway/sbom/manager/TestConstants.java, src/test/java/org/opensourceway/sbom/manager/utils/GiteeTest.java
=> feat: add api for download gitee repo archive

src/main/java/org/opensourceway/sbom/manager/batch/step/CollectStatisticsStep.java, src/main/java/org/opensourceway/sbom/manager/dao/LicenseRepository.java, src/main/java/org/opensourceway/sbom/manager/model/License.java, src/main/java/org/opensourceway/sbom/manager/model/ProductStatistics.java, src/main/java/org/opensourceway/sbom/manager/model/RawSbom.java, src/main/java/org/opensourceway/sbom/manager/service/license/impl/LicenseServiceImpl.java, src/test/java/SbomDataInitTest.java, src/test/java/org/opensourceway/sbom/manager/service/SbomServiceTest.java
=> Feat: collect product license statistics

src/main/java/org/opensourceway/sbom/manager/batch/step/CollectStatisticsStep.java, src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/main/java/org/opensourceway/sbom/manager/model/vo/PackageStatisticsVo.java, src/main/java/org/opensourceway/sbom/manager/model/vo/VulnerabilityVo.java, src/main/java/org/opensourceway/sbom/manager/service/SbomService.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/main/java/org/opensourceway/sbom/manager/utils/CvssSeverity.java, src/test/java/SbomDataInitTest.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java
=> Feat: query package statistics (vulnerability)

src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/main/java/org/opensourceway/sbom/manager/service/SbomService.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/main/java/org/opensourceway/sbom/manager/utils/PurlUtil.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, src/test/java/org/opensourceway/sbom/manager/service/PurlQueryConditionTest.java, src/test/java/org/opensourceway/sbom/manager/service/SbomServiceTest.java, src/test/java/org/opensourceway/sbom/manager/utils/VersionUtilTest.java, utils/src/main/java/org/opensourceway/sbom/utils/VersionUtil.java
=> Feat: version range search

src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/main/java/org/opensourceway/sbom/manager/model/vo/CopyrightVo.java, src/main/java/org/opensourceway/sbom/manager/model/vo/LicenseVo.java, src/main/java/org/opensourceway/sbom/manager/service/SbomService.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java
=> feat: add api to query license and copyright

clients/openeuler-repo/src/main/java/org/opensourceway/sbom/openeuler/obs/impl/RepoMetaParserImpl.java, src/main/java/org/opensourceway/sbom/manager/quartz/ScheduleBatchJobConfig.java, src/test/java/org/opensourceway/sbom/manager/utils/SbomPublishMock.java, src/test/resources/application.properties
=> fix: improve fetch repo robustness

clients/license/src/main/java/org/opensourceway/sbom/clients/license/vo/LicenseAndCopyright.java, doc/api/查询软件包license、copyright详情.md, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/main/java/org/opensourceway/sbom/manager/service/license/impl/LicenseServiceImpl.java, src/test/java/SbomDataInitTest.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, utils/src/main/java/org/opensourceway/sbom/constants/SbomConstants.java
=> set copyright  for pkg

analyzer/build.gradle.kts, analyzer/src/main/java/org/opensourceway/sbom/analyzer/model/GitData.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/parser/HttpParser.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/parser/handler/HandlerEnum.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/parser/handler/handlers/BaseGitHandler.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/parser/handler/handlers/GitCloneHandler.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/pkggen/AbstractPackageGenerator.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/pkggen/EximPackageGenerator.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/pkggen/GnuPackageGenerator.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/pkggen/JfrogPackageGenerator.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/pkggen/OmniosPackageGenerator.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/pkggen/PackageGenerator.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/pkggen/PythonPackageGenerator.java, analyzer/src/main/java/org/opensourceway/sbom/analyzer/pkggen/VcsPackageGenerator.java, src/main/resources/data.sql, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, src/test/resources/data.sql
=> Feat: integrate openGauss sbom

src/main/java/org/opensourceway/sbom/manager/dao/RepoMetaRepository.java, src/main/java/org/opensourceway/sbom/manager/model/RepoMeta.java, src/main/java/org/opensourceway/sbom/manager/quartz/ScheduleBatchJobConfig.java, src/test/java/org/opensourceway/sbom/manager/dao/RepoMetaRepositoryTest.java
=> fix: repoMeta table support openEuler multi version

clients/license/src/main/java/org/opensourceway/sbom/clients/license/vo/LicenseNameAndUrl.java, src/main/java/org/opensourceway/sbom/manager/batch/processor/sourceinfo/SupplySourceInfoProcessor.java, src/main/java/org/opensourceway/sbom/manager/batch/reader/license/ExtractLicenseReader.java, src/main/java/org/opensourceway/sbom/manager/batch/reader/sourceinfo/SupplySourceInfoReader.java, src/main/java/org/opensourceway/sbom/manager/batch/writer/sourceinfo/SupplySourceInfoWriter.java, src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/main/java/org/opensourceway/sbom/manager/dao/RepoMetaRepository.java, src/main/java/org/opensourceway/sbom/manager/quartz/ScheduleBatchJobConfig.java, src/main/java/org/opensourceway/sbom/manager/service/license/impl/LicenseServiceImpl.java, src/main/resources/spring-batch/sbom-read-job.xml, src/test/java/org/opensourceway/sbom/manager/dao/RepoMetaRepositoryTest.java, utils/src/main/java/org/opensourceway/sbom/constants/BatchContextConstants.java, utils/src/main/java/org/opensourceway/sbom/constants/BatchFlowExecConstants.java
=> feat: sbom import batch job add step for supply source info

src/main/java/org/opensourceway/sbom/manager/service/license/impl/LicenseServiceImpl.java, src/test/java/org/opensourceway/sbom/manager/service/SbomServiceTest.java, src/test/resources/data.sql
=> fix: fix dealOpenEulerPurl

analyzer/src/main/java/org/opensourceway/sbom/analyzer/TraceDataAnalyzer.java, src/main/java/org/opensourceway/sbom/manager/batch/reader/sourceinfo/SupplySourceInfoReader.java, src/main/java/org/opensourceway/sbom/manager/batch/step/TraceDataAnalyzerStep.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java
=> Feat: publish sboms of MindSpore & openGauss

src/main/java/org/opensourceway/sbom/manager/dao/ExternalVulRefRepository.java, src/test/java/SbomDataInitTest.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, src/test/java/org/opensourceway/sbom/manager/service/SbomServiceTest.java
=> Feat: order vuls by score/cve number/scoring system

src/main/java/org/opensourceway/sbom/manager/batch/reader/license/ExtractLicenseReader.java, src/main/java/org/opensourceway/sbom/manager/batch/writer/license/ExtractLicenseWriter.java, src/main/java/org/opensourceway/sbom/manager/service/license/LicenseService.java, src/main/java/org/opensourceway/sbom/manager/service/license/impl/LicenseServiceImpl.java, src/main/java/org/opensourceway/sbom/manager/utils/cache/LicenseInfoMapCache.java, src/test/java/org/opensourceway/sbom/manager/utils/SbomPublishMock.java, src/test/java/org/opensourceway/sbom/manager/utils/cache/CacheTest.java, src/test/java/org/opensourceway/sbom/manager/utils/cache/CacheTestConstant.java, src/test/java/org/opensourceway/sbom/manager/utils/cache/CaffeineCacheMultiKeyTest.java, src/test/java/org/opensourceway/sbom/manager/utils/cache/CaffeineCacheReloadTest.java, utils/build.gradle.kts, utils/src/main/java/org/opensourceway/sbom/cache/config/CacheProperties.java, utils/src/main/java/org/opensourceway/sbom/cache/config/CaffeineCacheConfig.java, utils/src/main/java/org/opensourceway/sbom/cache/constant/CacheConstants.java, utils/src/main/java/org/opensourceway/sbom/constants/BatchContextConstants.java
=> feat: move license info map from spring batch context to cache

src/main/java/org/opensourceway/sbom/manager/service/checksum/impl/ChecksumServiceImpl.java, src/test/java/org/opensourceway/sbom/manager/service/ChecksumToGAVTest.java, utils/src/main/java/org/opensourceway/sbom/constants/SbomConstants.java
=> fix:sha1 may duplicate in maven repo

clients/openeuler-repo/src/main/java/org/opensourceway/sbom/openeuler/obs/impl/RepoMetaParserImpl.java, src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/test/java/org/opensourceway/sbom/manager/service/OpenEulerMetaParserTest.java
=> fix: not support spec macro %package_help

doc/api/查询软件包正向依赖项.md, src/main/java/org/opensourceway/sbom/manager/dao/ExternalPurlRefRepository.java, src/main/java/org/opensourceway/sbom/manager/model/spdx/ReferenceCategory.java, src/main/java/org/opensourceway/sbom/manager/model/vo/BinaryManagementVo.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, src/test/java/org/opensourceway/sbom/manager/service/SbomServiceTest.java, src/test/resources/sample/linux-repodata-sample-sbom.spdx.json
=> feat: add api to query runtime dependency

doc/api/查询制品软件包列表.md, doc/api/查询漏洞详情.md, src/main/java/org/opensourceway/sbom/manager/batch/step/CollectStatisticsStep.java, src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/main/java/org/opensourceway/sbom/manager/dao/PackageRepository.java, src/main/java/org/opensourceway/sbom/manager/model/Package.java, src/main/java/org/opensourceway/sbom/manager/model/PackageStatistics.java, src/main/java/org/opensourceway/sbom/manager/model/Product.java, src/main/java/org/opensourceway/sbom/manager/model/vo/PackageStatisticsVo.java, src/main/java/org/opensourceway/sbom/manager/model/vo/request/QuerySbomPackagesRequest.java, src/main/java/org/opensourceway/sbom/manager/service/SbomService.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/main/java/org/opensourceway/sbom/manager/utils/CvssSeverity.java, src/test/java/org/opensourceway/sbom/manager/service/ChecksumToGAVTest.java, src/test/java/org/opensourceway/sbom/manager/service/reader/impl/spdx/SpdxReaderTest.java, src/test/java/org/opensourceway/sbom/manager/utils/TestCommon.java, src/test/resources/sample/sample-spdx.json
=> Feat: query packages by vul severity, license id, etc.

src/main/java/org/opensourceway/sbom/manager/model/ExternalPurlRef.java, src/main/java/org/opensourceway/sbom/manager/model/Package.java, src/main/java/org/opensourceway/sbom/manager/model/SbomElementRelationship.java, src/main/resources/data.sql
[索引external_purl_ref_purl_idx验证数据.txt](https://github.com/opensourceways/sbom-service/files/9860535/external_purl_ref_purl_idx.txt)
[索引external_purl_ref_pkg_id_idx验证数据.txt](https://github.com/opensourceways/sbom-service/files/9860537/external_purl_ref_pkg_id_idx.txt)
[索引related_element_id验证数据.txt](https://github.com/opensourceways/sbom-service/files/9860540/related_element_id.txt)
[索引package_name_idx验证数据.txt](https://github.com/opensourceways/sbom-service/files/9860541/package_name_idx.txt)
=> perf: add index for model

doc/SUMMARY.md, doc/api/漏洞影响范围查询.md, src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/main/java/org/opensourceway/sbom/manager/dao/ExternalVulRefRepository.java, src/main/java/org/opensourceway/sbom/manager/model/echarts/Edge.java, src/main/java/org/opensourceway/sbom/manager/model/echarts/Graph.java, src/main/java/org/opensourceway/sbom/manager/model/echarts/Node.java, src/main/java/org/opensourceway/sbom/manager/model/echarts/NodeType.java, src/main/java/org/opensourceway/sbom/manager/model/vo/PackageUrlVo.java, src/main/java/org/opensourceway/sbom/manager/service/SbomService.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, src/test/resources/sample/sample-spdx.json
=> Feat: query vulnerability impact

doc/api/查询制品license详情.md, src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/main/java/org/opensourceway/sbom/manager/dao/LicenseRepository.java, src/main/java/org/opensourceway/sbom/manager/model/vo/LicenseVo.java, src/main/java/org/opensourceway/sbom/manager/service/SbomService.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/test/java/SbomDataInitTest.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, src/test/java/org/opensourceway/sbom/manager/service/SbomServiceTest.java
=> add the universal api to query license

doc/api/反向追溯链查询.md, src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/main/java/org/opensourceway/sbom/manager/dao/ExternalPurlRefRepository.java, src/main/java/org/opensourceway/sbom/manager/dao/PackageRepository.java, src/main/java/org/opensourceway/sbom/manager/dao/spec/ExternalPurlRefCondition.java, src/main/java/org/opensourceway/sbom/manager/dao/spec/ExternalPurlRefSpecs.java, src/main/java/org/opensourceway/sbom/manager/service/SbomService.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, src/test/java/org/opensourceway/sbom/manager/dao/ExternalPurlRefRepositoryTest.java, src/test/java/org/opensourceway/sbom/manager/service/SbomServiceTest.java, utils/src/main/java/org/opensourceway/sbom/constants/SbomConstants.java
=> feat: api support runtime dependency

src/main/java/org/opensourceway/sbom/manager/dao/LicenseRepository.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/main/resources/data.sql
=> feat: add openEuler product config

src/main/java/org/opensourceway/sbom/manager/service/license/impl/LicenseServiceImpl.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, src/test/java/org/opensourceway/sbom/manager/service/SbomServiceTest.java
=> feat: get license info base the rela of repo-package

src/main/java/org/opensourceway/sbom/manager/batch/step/CollectStatisticsStep.java, src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/main/java/org/opensourceway/sbom/manager/dao/ExternalVulRefRepository.java, src/main/java/org/opensourceway/sbom/manager/dao/VulnerabilityRepository.java, src/main/java/org/opensourceway/sbom/manager/model/vo/PackageStatisticsVo.java, src/main/java/org/opensourceway/sbom/manager/model/vo/VulnerabilityVo.java, src/main/java/org/opensourceway/sbom/manager/service/SbomService.java, src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, src/test/java/org/opensourceway/sbom/manager/service/SbomServiceTest.java
=> Fix: dedup vuls when collect statistics & reserve query package vuls api

src/main/java/org/opensourceway/sbom/manager/utils/PurlUtil.java, src/test/java/org/opensourceway/sbom/manager/service/PurlQueryConditionTest.java
=> Feat: query generic type package

src/main/java/org/opensourceway/sbom/manager/service/impl/SbomServiceImpl.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java, utils/src/main/java/org/opensourceway/sbom/constants/SbomConstants.java
=> Fix: range search pageable error

src/main/java/org/opensourceway/sbom/manager/service/reader/impl/spdx/SpdxReader.java
=> feat: remove duplicate pkg info in relationship

doc/api/查询制品license详情.md, src/main/java/org/opensourceway/sbom/manager/controller/SbomController.java, src/main/java/org/opensourceway/sbom/manager/dao/LicenseRepository.java, src/test/java/SbomDataInitTest.java, src/test/java/org/opensourceway/sbom/manager/controller/PkgQueryControllerTests.java
=> add orderBy param to /sbom-api/queryLicenseUniversalApi

clients/cve-manager/src/main/java/org/opensourceway/sbom/clients/cvemanager/impl/CveManagerClientImpl.java, clients/cve-manager/src/main/java/org/opensourceway/sbom/clients/cvemanager/model/ComponentReport.java, clients/cve-manager/src/main/java/org/opensourceway/sbom/clients/cvemanager/model/CveManagerVulnerability.java, clients/cve-manager/src/main/java/org/opensourceway/sbom/clients/cvemanager/model/IssueStatus.java, src/main/java/org/opensourceway/sbom/manager/batch/decider/SkipAnalyzeTraceDataDecider.java, src/main/java/org/opensourceway/sbom/manager/batch/processor/vul/ExtractCveManagerProcessor.java, src/main/java/org/opensourceway/sbom/manager/batch/processor/vul/ExtractOssIndexProcessor.java, src/main/java/org/opensourceway/sbom/manager/batch/reader/sourceinfo/SupplySourceInfoReader.java, src/main/java/org/opensourceway/sbom/manager/batch/step/SelectWaitRawSbomStep.java, src/main/java/org/opensourceway/sbom/manager/model/VulScoringSystem.java, src/main/java/org/opensourceway/sbom/manager/model/VulStatus.java, src/main/java/org/opensourceway/sbom/manager/service/reader/impl/spdx/SpdxReader.java, src/main/java/org/opensourceway/sbom/manager/service/vul/VulService.java, src/main/java/org/opensourceway/sbom/manager/service/vul/impl/CveManagerServiceImpl.java, src/main/java/org/opensourceway/sbom/manager/service/vul/impl/OssIndexServiceImpl.java, src/main/resources/application.properties, src/main/resources/cve-manager.properties, src/test/resources/application.properties, src/test/resources/cve-manager.properties, utils/src/main/java/org/opensourceway/sbom/constants/BatchContextConstants.java
=> Chore: modify cve-manager data process

src/main/java/org/opensourceway/sbom/manager/model/Sbom.java, src/main/java/org/opensourceway/sbom/manager/model/spdx/FileType.java, src/main/java/org/opensourceway/sbom/manager/service/writer/impl/spdx/SpdxWriter.java, src/test/java/SbomDataInitTest.java, src/test/java/org/opensourceway/sbom/manager/controller/ExportControllerTests.java, src/test/java/org/opensourceway/sbom/manager/utils/TestCommon.java
=> feat: export sbom support upstream and patch info

src/main/java/org/opensourceway/sbom/manager/service/checksum/impl/ChecksumServiceImpl.java, src/main/java/org/opensourceway/sbom/manager/utils/cache/ChecksumSkipMapCache.java, src/main/resources/application.properties, src/main/resources/maps/checksumSkipMap.yml, utils/src/main/java/org/opensourceway/sbom/cache/constant/CacheConstants.java, utils/src/main/java/org/opensourceway/sbom/constants/SbomConstants.java
=> feat: add blacklist config to get GAV info from checksum

src/main/java/org/opensourceway/sbom/manager/model/spdx/SpdxDocument.java, src/test/java/SbomDataInitTest.java
=> fix: add constructor for fasterxml deserialize

src/main/java/org/opensourceway/sbom/manager/model/spdx/SpdxDocument.java, src/main/java/org/opensourceway/sbom/manager/model/spdx/SpdxPackage.java
=> fix: fasterxml can't deserialize SpdxDocument

src/main/java/org/opensourceway/sbom/manager/batch/reader/vul/ExternalPurlRefListReader.java, src/main/java/org/opensourceway/sbom/manager/model/spdx/ReferenceCategory.java
error info:
{
"code": 400,
"message": "Missing coordinates version"
}
=> fix: upstream purl not extract purl

src/main/java/org/opensourceway/sbom/manager/batch/pojo/SupplySourceInfo.java, src/main/java/org/opensourceway/sbom/manager/batch/processor/sourceinfo/SupplySourceInfoProcessor.java, src/main/java/org/opensourceway/sbom/manager/batch/writer/sourceinfo/SupplySourceInfoWriter.java, src/main/java/org/opensourceway/sbom/manager/dao/SbomElementRelationshipRepository.java, src/main/java/org/opensourceway/sbom/manager/model/ExternalPurlRef.java, src/main/java/org/opensourceway/sbom/manager/model/File.java
=> fix: remove duplicate at supplySourceInfo

src/main/resources/spring-batch/sbom-read-job.xml
fix: modify spring batch chunk from singleton to prototype for thread safety
=> fix: modify spring batch chunk from singleton to prototype for thread safety

clients/vcs/src/main/java/org/opensourceway/sbom/clients/vcs/gitee/GiteeApi.java, src/main/java/org/opensourceway/sbom/manager/batch/processor/sourceinfo/SupplySourceInfoProcessor.java, src/main/java/org/opensourceway/sbom/manager/batch/writer/license/ExtractLicenseWriter.java, src/main/java/org/opensourceway/sbom/manager/service/license/LicenseService.java, src/main/java/org/opensourceway/sbom/manager/service/license/impl/LicenseServiceImpl.java, utils/src/main/java/org/opensourceway/sbom/utils/OpenEulerAdvisorParser.java
=> perf: modify logger format

clients/openeuler-repo/src/main/java/org/opensourceway/sbom/openeuler/obs/OpenEulerRepoCache.java, clients/openeuler-repo/src/main/java/org/opensourceway/sbom/openeuler/obs/RepoMetaParser.java, clients/openeuler-repo/src/main/java/org/opensourceway/sbom/openeuler/obs/SbomRepoConstants.java, clients/openeuler-repo/src/main/java/org/opensourceway/sbom/openeuler/obs/impl/RepoMetaParserImpl.java, clients/openeuler-repo/src/main/java/org/opensourceway/sbom/openeuler/obs/vo/RepoInfoVo.java, clients/vcs/src/main/java/org/opensourceway/sbom/clients/vcs/VcsApi.java, clients/vcs/src/main/java/org/opensourceway/sbom/clients/vcs/gitee/GiteeApi.java, clients/vcs/src/main/java/org/opensourceway/sbom/clients/vcs/gitee/model/GiteeBranchInfo.java, src/main/java/org/opensourceway/sbom/manager/model/RepoMeta.java, src/main/java/org/opensourceway/sbom/manager/service/repo/impl/RepoServiceImpl.java, src/test/java/org/opensourceway/sbom/manager/service/OpenEulerMetaParserTest.java, src/test/java/org/opensourceway/sbom/manager/service/RepoServiceTest.java, src/test/java/org/opensourceway/sbom/manager/utils/GiteeTest.java, utils/src/main/java/org/opensourceway/sbom/cache/constant/CacheConstants.java
=> refactor: improve the efficiency of openEuler fetch repo meta

src/main/java/org/opensourceway/sbom/manager/dao/PackageMetaRepository.java, src/main/java/org/opensourceway/sbom/manager/model/PackageMeta.java, src/main/java/org/opensourceway/sbom/manager/service/checksum/impl/ChecksumServiceImpl.java, src/main/resources/maps/checksumSkipMap.yml
=> Chore: save maven gav to db

src/main/java/org/opensourceway/sbom/manager/batch/processor/license/ExtractLicensesProcessor.java, src/main/java/org/opensourceway/sbom/manager/batch/step/CollectStatisticsStep.java, src/main/java/org/opensourceway/sbom/manager/batch/step/FillUpLicenseStep.java, src/main/java/org/opensourceway/sbom/manager/dao/PkgLicenseRelpRepository.java, src/main/java/org/opensourceway/sbom/manager/model/License.java, src/main/java/org/opensourceway/sbom/manager/model/Package.java, src/main/java/org/opensourceway/sbom/manager/model/PkgLicenseRelp.java, src/main/resources/application.properties, src/test/java/SbomDataInitTest.java
=> Perf: change table structure of pkg_license_relp

src/test/java/SbomDataInitTest.java, src/test/java/org/opensourceway/sbom/manager/service/OpenEulerMetaParserTest.java
=> Test: fix ut

cache/src/main/java/org/opensourceway/sbom/cache/LicenseObjectCache.java
=> fix: fix bug when get a new license

cache/src/main/java/org/opensourceway/sbom/cache/LicenseObjectCache.java
=> fix: update license url for old license data

batch/src/main/java/org/opensourceway/sbom/batch/step/FillUpLicenseStep.java, src/main/java/org/opensourceway/sbom/service/license/impl/LicenseServiceImpl.java
=> Fix: get spdx license id when fill up license

batch/src/main/java/org/opensourceway/sbom/batch/processor/license/ExtractLicensesProcessor.java, batch/src/main/java/org/opensourceway/sbom/batch/processor/sourceinfo/SupplySourceInfoProcessor.java, cache/src/main/java/org/opensourceway/sbom/cache/OpenEulerRepoMetaCache.java, cache/src/main/java/org/opensourceway/sbom/cache/RepoMetaLicenseCache.java, cache/src/main/java/org/opensourceway/sbom/cache/constant/CacheConstants.java, utils/build.gradle.kts, utils/src/main/java/org/opensourceway/sbom/utils/RepoMetaUtil.java
=> feat: get license cache from repoMeta with a universal method
